import { Link } from 'react-router-dom'
import { Eye, EyeOff, Globe2, Lock, Mail, Search, Share2, User } from 'lucide-react'
import { useState } from 'react'

const Brand = () => <Link to="/" className="flex items-center gap-3 text-[27px] font-semibold tracking-tight text-[#0756c9]"><span className="grid h-[46px] w-[46px] place-items-center rounded-[4px] bg-[#0756c9] text-white"><svg viewBox="0 0 24 24" className="h-6 w-6 fill-none stroke-current" strokeWidth="2.1"><path d="M7 20v-7h10v7M6 4h12v4H6zM8 8v5m8-5v5M9 17h6" strokeLinecap="round" strokeLinejoin="round" /></svg></span>FurniMarket</Link>

const Links = ({ title, links }) => <div><p className="text-[16px] font-bold tracking-wide text-[#2d3649]">{title}</p><ul className="mt-5 space-y-3 text-[16px] text-[#626a7b]">{links.map((link) => <li key={link}><a href="#footer">{link}</a></li>)}</ul></div>

export default function Signup() {
  const [showPassword, setShowPassword] = useState(false)

  return <main className="min-h-screen overflow-x-hidden bg-[#fbfaff] font-sans text-[#2d3649]">
    <header className="border-b border-[#d8d9e1] bg-[#fcfbff]"><div className="flex h-[106px] items-center gap-8 px-7"><Brand /><label className="ml-4 hidden h-[51px] w-[414px] items-center rounded-xl border border-[#c6cada] bg-[#f4f5ff] px-5 text-[#50586c] md:flex"><Search size={23} className="mr-1" /><input aria-label="Search vendors and furniture" placeholder="Search for vendors, furniture or styles..." className="min-w-0 flex-1 bg-transparent text-[17px] outline-none" /></label><nav className="ml-auto hidden items-center gap-9 text-[17px] font-semibold lg:flex"><Link to="/browse-vendors">Browse Vendors</Link><a href="#categories">Categories</a><a href="#how-it-works">How it Works</a><Link to="/login" className="ml-6 text-[#0756c9]">Login</Link><Link to="/signup" className="rounded-md bg-[#0756c9] px-7 py-[10px] text-white">Sign Up</Link></nav></div></header>
    <section className="grid min-h-[760px] border-b border-[#d1d3dd] lg:grid-cols-2">
      <div className="min-h-[420px] bg-cover bg-center" role="img" aria-label="Modern living room" style={{ backgroundImage: "linear-gradient(180deg,rgba(23,25,38,.05) 42%,rgba(17,20,31,.76)),url('https://images.unsplash.com/photo-1618221195710-dd6b41faa6?auto=format&fit=crop&w=1200&q=90')" }} />
      <div className="flex items-center justify-center px-6 py-16 sm:px-12">
        <div className="w-full max-w-[440px]">
          <p className="text-sm font-semibold tracking-[.16em] text-[#0756c9]">JOIN FURNIMARKET</p>
          <h1 className="mt-3 text-4xl font-semibold tracking-tight text-[#273145]">Create your account</h1>
          <p className="mt-3 text-[16px] leading-6 text-[#687084]">Discover local furniture makers and save the pieces you love.</p>
          <form className="mt-8 space-y-5" onSubmit={(event) => event.preventDefault()}>
            <label className="block text-sm font-semibold text-[#40495d]">Full name<div className="mt-2 flex h-12 items-center rounded-md border border-[#cbd0dc] bg-white px-3 focus-within:border-[#0756c9] focus-within:ring-2 focus-within:ring-blue-100"><User size={18} className="mr-2 text-[#7a8293]" /><input required type="text" name="name" autoComplete="name" placeholder="Your full name" className="min-w-0 flex-1 bg-transparent text-[15px] font-normal outline-none placeholder:text-[#9aa0af]" /></div></label>
            <label className="block text-sm font-semibold text-[#40495d]">Email address<div className="mt-2 flex h-12 items-center rounded-md border border-[#cbd0dc] bg-white px-3 focus-within:border-[#0756c9] focus-within:ring-2 focus-within:ring-blue-100"><Mail size={18} className="mr-2 text-[#7a8293]" /><input required type="email" name="email" autoComplete="email" placeholder="you@example.com" className="min-w-0 flex-1 bg-transparent text-[15px] font-normal outline-none placeholder:text-[#9aa0af]" /></div></label>
            <label className="block text-sm font-semibold text-[#40495d]">Password<div className="mt-2 flex h-12 items-center rounded-md border border-[#cbd0dc] bg-white px-3 focus-within:border-[#0756c9] focus-within:ring-2 focus-within:ring-blue-100"><Lock size={18} className="mr-2 text-[#7a8293]" /><input required type={showPassword ? 'text' : 'password'} name="password" autoComplete="new-password" placeholder="At least 8 characters" className="min-w-0 flex-1 bg-transparent text-[15px] font-normal outline-none placeholder:text-[#9aa0af]" /><button type="button" onClick={() => setShowPassword((shown) => !shown)} aria-label={showPassword ? 'Hide password' : 'Show password'} className="text-[#6d768a]">{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>
            <label className="flex items-start gap-2 text-sm leading-5 text-[#687084]"><input required type="checkbox" className="mt-0.5 h-4 w-4 rounded border-slate-300 accent-[#0756c9]" />I agree to the <a href="#terms" className="text-[#0756c9]">Terms of Service</a> and <a href="#privacy" className="text-[#0756c9]">Privacy Policy</a>.</label>
            <button type="submit" className="h-12 w-full rounded-md bg-[#0756c9] text-[16px] font-semibold text-white transition hover:bg-blue-800">Create account</button>
          </form>
          <p className="mt-6 text-center text-sm text-[#687084]">Already have an account? <Link to="/login" className="font-semibold text-[#0756c9]">Log in</Link></p>
        </div>
      </div>
    </section>
    <footer id="footer" className="bg-white pt-[74px]"><div className="grid gap-12 px-7 pb-[88px] sm:grid-cols-2 lg:grid-cols-[1.25fr_1.2fr_1.25fr_1.15fr] lg:gap-12"><div><Brand /><p className="mt-5 max-w-[305px] text-[16px] leading-[1.42] text-[#626a7b]">Connecting local furniture artisans with homeowners looking for quality, handcrafted excellence.</p><div className="mt-7 flex gap-6 text-[#71798b]"><Globe2 size={25} /><Share2 size={25} /><Mail size={25} /></div></div><Links title="THE COMPANY" links={['About Us', 'Careers', 'Press Kit', 'Support']} /><Links title="MARKETPLACE" links={['Browse Vendors', 'Style Guide', 'Buyer Protection', 'Vendor Login']} /><div><p className="text-[16px] font-bold tracking-wide">STAY INSPIRED</p><p className="mt-5 max-w-[290px] text-[16px] leading-[1.35] text-[#626a7b]">Get interior design tips and local artisan highlights.</p><form className="mt-5 flex h-[44px] overflow-hidden rounded-md border border-[#c6cada]"><input aria-label="Your email" placeholder="Your email" className="min-w-0 flex-1 bg-[#f0f2ff] px-3 text-[16px] outline-none" /><button className="w-[65px] bg-[#0756c9] text-[14px] font-semibold text-white">Join</button></form></div></div><div className="mx-7 border-t border-[#d5d8e1]" /><div className="flex justify-between px-7 py-10 text-[16px] text-[#848b9c]"><span>© 2024 FurniMarket Marketplace. All rights reserved.</span><span className="flex gap-10"><a href="#privacy">Privacy Policy</a><a href="#terms">Terms of Service</a></span></div></footer>
  </main>
}
